---
version: 0.2

env:
  variables:
    GLUE_IMAGE: "amazon/aws-glue-libs:5"
    WHEEL_BUCKET: "cicd-pytest-bucket"
    GLUE_JOB_NAME: "CICD-glue-poc"
    AUTO_DEPLOY: "false"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Upgrading pip and tools..."
      - pip install --upgrade pip setuptools wheel pytest

  pre_build:
    commands:
      - echo "Checking source directory..."
      - echo "$CODEBUILD_SRC_DIR"
      - ls -la
      - echo "=== RUN DOCKER ==="
      - >
          docker run -d
          -v "$CODEBUILD_SRC_DIR":/home/glue_user/workspace
          -e DISABLE_SSL=true -p 4040:4040 -p 18080:18080
          --entrypoint /bin/bash
          --name glue_pyspark
          "$GLUE_IMAGE"
          -c "tail -f /dev/null"
      - echo "=== Wait for container to be up ==="
      - |
        for i in {1..10}; do
          if [ "$(docker ps -q -f name=glue_pyspark)" ]; then
            echo "Container is running!"
            break
          fi
            echo "Waiting for container..."
            sleep 3
        done
      - echo "=== container start up completed ==="
  build:
    commands:
      - echo "=== EXEC into DOCKER ==="
      - docker ps -a
      - docker inspect glue_pyspark
      - |
        docker exec glue_pyspark bash -c "
          pwd &&
          cd /home/glue_user/workspace &&
          pwd &&
          ls -la &&
          pytest -v
        "
  post_build:
    commands:
      - echo "=== Stop & remove docker container ==="
      - docker stop glue_pyspark
      - docker rm glue_pyspark
      - echo "=== UPLOAD WHEEL TO S3 ==="


artifacts:
  files:
    - dist/*.whl
