---
version: 0.2

env:
  variables:
    GLUE_IMAGE: "amazon/aws-glue-libs:5"
    WHEEL_BUCKET: "cicd-pytest-bucket"
    GLUE_JOB_NAME: "CICD-glue-poc"
    AUTO_DEPLOY: "false"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Upgrading pip and tools..."
      - pip install --upgrade pip setuptools wheel pytest boto3

  pre_build:
    commands:
      - echo "Checking source directory..."
      - echo "$CODEBUILD_SRC_DIR"
      - ls -la
      - mkdir -p reports
      - chmod 777 reports
      - echo "=== RUN DOCKER ==="
      - >
          docker run -d
          -v "$CODEBUILD_SRC_DIR":/home/glue_user/workspace
          -v "$CODEBUILD_SRC_DIR/reports":/home/glue_user/workspace/reports
          -e DISABLE_SSL=true -p 4040:4040 -p 18080:18080
          --entrypoint /bin/bash
          --name glue_pyspark
          "$GLUE_IMAGE"
          -c "tail -f /dev/null"
      - echo "=== Wait for container to be up ==="
      - |
        for i in {1..10}; do
          if [ "$(docker ps -q -f name=glue_pyspark)" ]; then
            echo "Container is running!"
            break
          fi
            echo "Waiting for container..."
            sleep 3
        done
      - echo "=== container start up completed ==="
  build:
    commands:
      - echo "=== EXEC into DOCKER for pysparkUnitTests ==="
      - docker ps -a
      - |
        docker exec glue_pyspark bash -c "
          pwd &&
          export PYTHONPATH=/home/glue_user/workspace &&
          cd /home/glue_user/workspace/tests/pysparkUnitTests &&
          pwd &&
          ls -la &&
          pytest -v \
            --junitxml=/home/glue_user/workspace/reports/test-results.xml \
        " || TEST_EXIT_CODE=$?
        echo "Pytest exit code: ${TEST_EXIT_CODE:-0}"
        if [ "${TEST_EXIT_CODE:-0}" -ne 0 ]; then
        echo "Some tests failed. Reports will still be uploaded."
        fi
      - echo "=== RUNNING integration tests on buildspec ==="
      - cd tests/integration
      - ls -la
      - |
        pytest -v \
          --junitxml=/home/glue_user/workspace/reports/i-test-results.xml \
          || INTEGRATION_EXIT_CODE=$?
      - if [ "${INTEGRATION_EXIT_CODE:-0}" -ne 0 ]; then
          echo "Some integration tests failed. Reports will still be uploaded."
        fi

  post_build:
    commands:
      - echo "=== Stop & remove docker container ==="
      - docker stop glue_pyspark
      - docker rm glue_pyspark
      - echo "=== UPLOAD WHEEL TO S3 ==="
reports:
  pytest_reports:
    files:
      - reports/test-results.xml
    file-format: JUNITXML


artifacts:
  files:
    - dist/*.whl
